# Generated by Django 5.0.4 on 2025-12-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('grade', 'room', 'school')},
        ),
    ]
